name: Manual BF Art Competition Contract Release
on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Unique release name (e.g., v1.0.2)'
        required: true
        type: string

permissions:  # required permissions for the workflow
  id-token: write
  contents: write
  attestations: write

jobs:
  release-bf-competition:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
    with:
      release_name: ${{ github.event.inputs.release_name }}
      release_description: 'BF Art Competition Contract Release - Soroban smart contract for managing art competitions with voting and prize distribution'
      relative_path: 'bf_competition'
      package: 'bf_competition'
      home_domain: 'brainfrog.art'  # Replace with your actual domain
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}
