name: BF Art Competition Contract
on:
  push:
    tags:
      - 'v*'  # triggered whenever a new tag (prefixed with "v") is pushed to the repository

jobs:
  release-bf-competition:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
    with:
      release_name: ${{ github.ref_name }}
      release_description: 'BF Art Competition Contract Release - Soroban smart contract for managing art competitions with voting and prize distribution'
      relative_path: bf_competition
      package: 'bf_competition'
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}
